### ISSUE TITLE
How the heck is `DocumentFragment` slower than `appendChild()`? ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#1]
I was under the interpretation that the `DocumentFragment` was faster.
Benchmark: https://jsperf.com/appendchild-vs-documentfragment-vs-innerhtml/15

https://github.com/devpunks/snuggsi/blob/master/benchmark.js

![capture d ecran 2017-02-17 a 03 53 56](https://cloud.githubusercontent.com/assets/38223/23058907/25941af2-f4c5-11e6-8888-c3c0351a7e9e.png)

**Comment by brandondees** [comment]
may want to spend some more time on that site, you're linking to version 15 of 130 different benchmark variations. might need to craft your own for serious comparison

**Comment by tmornini** [comment]
I agree with @brandondees.

Benchmark result times under 3ms are within noise limits.

I'd recommend benching it over a longer time period...

**Comment by brandondees** [comment]
yeah. also just a single run is almost meaningless. you gotta take the Nth percentile of numerous benchmark runs to filter out the basic noise levels. don't forget that different computers run at different speeds.

**Comment by tmornini** [comment]
@brandondees Wow, good catch, single iterations are meaningless.
