### ISSUE TITLE
OWNERS

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#106]
Any setup help with this would be appreciated @pachonk. Fairly new feature. /cc @tmornini 

https://github.com/blog/2392-introducing-code-owners

**Comment by brandondees** [comment]
lets you whitelist specific required maintainers for given areas of code, file or directory or whatever. for example you can have the original author of each example component be the owner of that example directory, then any changes to that code have a required review by them specifically

**Comment by pachonk** [comment]
And it can be a glob.

**Comment by tmornini** [comment]
While I appreciate this feature for certain cases, it seems needlessly restrictive for this project at this stage.

**Comment by pachonk** [comment]
I agree with Tom

**Comment by tmornini** [comment]
@snuggs give me the word and I'll enable protected master.

**Comment by snuggs** [comment]
@tmornini Do what's best for the project. :-). Truth be told saw WHATWG implement it. Agree too early. See this is why I <3 you guys. I can handle the dirty work. But GUIDANCE. I'm a running back not a quarterback. Tell me the play and i score the touchdown. The only "play" I know is a free for all scramble. HEHE ![](http://i.imgur.com/BK4SF4S.gifv)

**Comment by tmornini** [comment]
![No guidance](http://gph.is/1cqCKOd)

**Comment by tmornini** [comment]
We can add Require Status Checks after #101 merges.

![screen shot 2017-07-13 at 2 20 39 pm](https://user-images.githubusercontent.com/87/28188368-c694299a-67d6-11e7-9d0e-5f61b62823b0.png)

**Comment by pachonk** [comment]
Let's also restrict who can push to master to only admins

**Comment by tmornini** [comment]
@pachonk That option is a misnomer.

As configured, Github will only allows PRs to be merged to master and never allow direct pushes.

That check box means only certain users can merge to master AFTER status checks succeed, including having received a review.

```
ruby: system | git: master %
snuggsi $ touch bobs-your-uncle
ruby: system | git: master %
snuggsi $ git add bobs-your-uncle
ruby: system | git: master +
snuggsi $ git commit -m 'bobs-your-uncle'
[master fe1b3ec] bobs-your-uncle
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 bobs-your-uncle
ruby: system | git: master
snuggsi $ git push
Counting objects: 2, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 277 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least one approved review is required by reviewers with write access.
To github.com:devpunks/snuggsi.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:devpunks/snuggsi.git'
```

**Comment by tmornini** [comment]
Oh, also added this:

![screen shot 2017-07-13 at 8 08 20 pm](https://user-images.githubusercontent.com/87/28196725-5213dad0-6807-11e7-9d5b-a7b8f2af17d0.png)

**Comment by pachonk** [comment]
I actually much prefer "merge commits" as the goto merge option because it marks a commit with a link to the PR for later ref.
Not trying to change any workflow, just wanted to bring that up.

**Comment by tmornini** [comment]
@pachonk Interesting. I know @snuggs loves the fast-forward merges. ❤️

**Comment by snuggs** [comment]
I have a "left handed" idea. What if we flip the bitcoin. What if the PR merely links to a bonafied tag. If we are mergin' prolly releasin' DEFINITELY taggin' so we already are doing that. Now mind you @tmornini actually i've not minded them more and more (when working with other people). 

My default will always be "Do what's best for the community". My suggestion is above. 

What do ya think?
