### ISSUE TITLE
<exit-modal>

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#107]
# <exit-modal>
"Before You Go" exit popup. <<< I **HATE** that word hence no `<exit-popup>`. Hate is a strong word. But I can say I HATE that word.

## Specification
Simple implementation logic wise. More heavy on the CSS [See `<github-ribbon>` for similar pattern](https://github.com/devpunks/snuggsi/tree/master/examples/github-ribbon)

## References
- https://www.conversioner.com/glossary/exit-popup
- http://www.icegram.com/wordpress-exit-popup

**Comment by brandondees** [comment]
why's this on the list? i recognize it's useful for sales numbers but it's clearly user-hostile, too.

**Comment by mrbernnz** [comment]
@brandondees What makes the phrasing hostile?
@snuggs does this help? [display boxes explanation](https://ux.stackexchange.com/questions/90336/whats-the-difference-between-a-modal-popup-popover-and-lightbox)

**Comment by brandondees** [comment]
I didn't say the phrasing is hostile, the actual page behavior is. They wanted to close it but you blocked them.

**Comment by tmornini** [comment]
@brandondees I couldn't agree more!

Whenever I see crap like that I immediately think "yes, of course! That's why I closed the fucking page!"

**Comment by snuggs** [comment]
Dually noted @tmornini @brandondees @mrbernnz
