### ISSUE TITLE
Update gzip compression algorithm

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#11]
Currently using gzip for compression. @brandondees proposes brotli. I'm all for the experiment.

Helpful script will be
`$ npm run compile`
This is script makes the sausage in the factory.
https://github.com/devpunks/snuggsi/blob/master/package.json#L48

This runs entire build step and leaves an artifact in the `./dist/snuggsi.min.es` location.

Can clobber current `gzip` script within `package.json`. Also using duplicate script for `weigh` script.

https://github.com/devpunks/snuggsi/blob/master/package.json#L56-L60

**Comment by snuggs** [comment]
Support Table. http://caniuse.com/#feat=brotli

![capture d ecran 2017-04-14 a 04 09 17](https://cloud.githubusercontent.com/assets/38223/25037631/3855eed4-20c8-11e7-8207-07d8fd63ff19.png)

**Comment by brandondees** [comment]
i tossed in a `npm run brotli` command to experiment with compressing just the snuggsi.es file, presuming you have brotli pre-installed from source or homebrew or whatever. we can update to apply the command to any uncompressed files ready to be packaged for distribution. the web server will have to be configured to respect the accept-encoding header for selecting specific compressed static file types, and/or to apply on-the-fly compression to outgoing resources, which is less advantageous but still better than no compression happening.

**Comment by snuggs** [comment]
This works great! closing issue as it's already being used in the `npm run compile` and `npm run weigh` steps now.

Thank you !
