### ISSUE TITLE
move https://devpunks.herokuapp.com/typography.css as used in examples to either an available CDN or to a repo-local file

### ISSUE THREAD

**Issue by brandondees** [devpunks/snuggsi#110]
the free heroku dyno takes a while to wake up whenever it's idle, which makes dev / test on these examples really annoying. the other hosted assets are on cdn locations but not the typography stylesheet

**Comment by snuggs** [comment]
I know.... I know.... :thinking:

**Comment by snuggs** [comment]
@brandondees fixed in #185
