### ISSUE TITLE
Custom Elements Native Shim Polyfill

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#127]
@brandondees this and #123 basically take care of our needs with the custom elements spec. We primarily use HTML Imports and Custom Elements. To be clear this is due to the fact there are some issues with transpiling and inheriting from HTMLElement. Please read comments. https://github.com/doug/custom-elements/blob/90e5c720ca8ea9338baf30bb74b6a5d3f5cf61bb/src/native-shim.js

## References
  - Webcomponents js Custom elements polyfill - https://github.com/webcomponents/custom-elements
  - Custom Elements MDN - https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements
  - Direct W3C recommendation on implementation - https://github.com/w3c/webcomponents/issues/423
  - SO on babel extends - https://stackoverflow.com/questions/33870684/why-doesnt-instanceof-work-on-instances-of-error-subclasses-under-babel-node/33877501#answer-33877501
  - Workaround - https://github.com/babel/babel/issues/3083#issuecomment-315569824
  - https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend

**Comment by brandondees** [comment]
any issues to address with this or is it just a "to do"?

**Comment by snuggs** [comment]
Thanks @brandondees forgot the labels

**Comment by snuggs** [comment]
Sheds light on solution. From the spec maintainers. And their frustration with polyfill authors https://github.com/whatwg/html/issues/1704 Particularly https://github.com/whatwg/html/issues/1704#issuecomment-241881091

**Comment by snuggs** [comment]
@brandondees @@0xhjohnson we can actually close this out when we complete #187. As of 2018 we are completely independent of the web components polyfill (thank goodness).
