### ISSUE TITLE
Mountain View gem integration

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#128]
https://github.com/devnacho/mountain_view

This could be nice overlap into rails projects. Sinatra if I discover mountain view is merely middleware.

/cc @pachonk @brandondees https://github.com/devnacho/mountain_view/issues/55

**Comment by robcole** [comment]
❤️ 

I've got some interest in this, or in the possibility of something mountain_view esque depending on the goals. MV is an engine and definitely more "Rails" than ruby, so the real question would be what the end goal is for integrating with it is. We'll officially be using some snuggsi components in production pretty soon, and I'd be happy to share whatever patterns come out of how we start building it (currently we're doing this through Mountain View, but are investigating other techniques for the next few components).

**Comment by brandondees** [comment]
keep us posted on any findings @robcole i started experimenting with MV this week on a project and I find it pretty handy so far but there's the bigger question of how difficult it will be to break away from the dependency if that becomes necessary.

I also still have some uncertainties about how nicely it integrates with e.g. snuggsi for SSR + CSR components... I think it might need to support multiple yield blocks to handle higher order components effectively enough, but i don't see a way of accomplishing that yet.

**Comment by snuggs** [comment]
@robcole @brandondees i feel like middleware is the answer. I mean right now all MV is is conventions around coupling implementation details within well named directories. Truth be told this was/is my ONLY gripe with Rails. Feels like this looking for things sometimes 🐱 >> https://www.youtube.com/watch?v=q1XlhSjbgWI

**Comment by brandondees** [comment]
well there's definitely some more things going on like `render_component`
handling etc. and all the styles and scripts get added to the global asset
bundles instead of having to track all that by hand. if we replace the
whole rails view layer with a component oriented middleware, that might
work, but that might also be a bigger overall endeavor.
