### ISSUE TITLE
What does the github pages compilation mean?

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#13]
@pachonk have any idea what is happening here? Seemed to start happening 3 commits ago.
![capture d ecran 2017-04-16 a 20 07 44](https://cloud.githubusercontent.com/assets/38223/25075348/9dec5caa-22e0-11e7-8507-135094462a05.png)

**Comment by pachonk** [comment]
Is there a GitHub pages associated with that repo?

**Comment by snuggs** [comment]
@pachonk i dunno i think so. I believe i set one up but why would it start 3 commits ago?

**Comment by pachonk** [comment]
When was github pages first turned on. A combo of docs folder and being turned on in the settings page is probably the case.

**Comment by snuggs** [comment]
That's something you can help with. That stuff and like github.io. I've been working moving stuff from readme to the wiki. Any feedback is appreciated @pachonk. Don't worry about not knowing all the features of the library. we even have a domain name `snuggsi.es` i think you said that can point to github.io pages. 

Closing this issue for now as you cleared it up. Feel free to create another one for the github.io pages.

#salute 🙏
