### ISSUE TITLE
Hello World demo's onClick event doesn't work

### ISSUE THREAD

**Issue by neiljohari** [devpunks/snuggsi#131]
[Clicking on the JSFiddle for the Hello World Demo](https://jsfiddle.net/rmv8e2vz/), the code indicates that clicking the `hello-world` element rendered should create an alert box. However, clicking on the text displayed causes nothing to happen.

It's important to fix this soon since the Hello World Demo is the first impression of snuggsi for many.

**Comment by snuggs** [comment]
@neiljohari please review #132
