### ISSUE TITLE
TypeError: window.customElements is undefined (Firefox)

### ISSUE THREAD

**Issue by robcole** [devpunks/snuggsi#137]
Currently occurs in Firefox (latest - 55.0.3 / OSX). Can be replicated on examples in cloned repo.

This appears to be preventing snuggsi from working in FF. Currently paired with `webcomponents-lite.js` but have attempted other polyfills (`webcomponents-hi-ce` etc), none of which appears to be working.

## Firefox Bugzilla Ticket Tracker Reference
  - https://bugzilla.mozilla.org/show_bug.cgi?id=889230

**Comment by robcole** [comment]
Things to note (this is in a production use-case, not in our current examples):

When using Firefox and disabling web components (in `about:config`), then loading the polyfill *before* snuggsi (this part is unclear in the README.md - would like to clarify documentation there), I am able to load the component; however, template binding/interpolation is not working.

Will add more info as I debug further.

**Comment by snuggs** [comment]
🎉 WOOT for finding this @robcole. On it like white on rice. /cc @brandondees

**Comment by snuggs** [comment]
@robcole also fair to note (as mentioned in slack) the high priority right now is THIS ticket and https://github.com/devpunks/snuggsi/pull/136 which both will address all of your concerns. (The latter is re: to your template issues). Expected turnaround is anyday (starting tomorrow). I did about 80% of the work on the later of the two this past weekend.

**Comment by snuggs** [comment]
@robcole found it! Looks like we at least can reference where bug is in Firefox. Will update this description as well. And associate with Pull Request for archival's sake.

https://bugzilla.mozilla.org/show_bug.cgi?id=889230

**Comment by snuggs** [comment]
@robcole  Closing due to being fixed since polyfill removal back in August/September.
