### ISSUE TITLE
Documentation on polyfill load order is unclear

### ISSUE THREAD

**Issue by robcole** [devpunks/snuggsi#138]
Docs state:

> Place the <script name=polyfill … > below before snuggsiツ for evergreen cross-browser support.

Code example shows:

```
<!-- snuggsiツ (modern) -->
<script nomodule src=//unpkg.com/snuggsi></script>

<!-- webcomponents polyfill -->
<script
  name=polyfill
  src=//cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.0.0/webcomponents-hi-ce.js>
</script>
```

I think the "before below snuggsi" is unclear and causing confusion (at least for me) here. I'd assume the polyfill would be loaded first, but the code example seems to show it in loading last. Thoughts on a change here?

**Comment by brandondees** [comment]
I was confused in the same way. I _think_ it should read:
> Place the polyfill script tag _before_ snuggsi, as shown below
and then actually show it loading before.

I'd have to double check to make sure that it works that way and whether it breaks in the reverse order.

**Comment by snuggs** [comment]
Actually order is irrelevant @robcole @brandondees. We run zero code until the author calls the `Element` tagged template helper. 
```
Element `foo-bar` (...)
```
So i found out order is superfluous. Was a pleasant surprise too.

**Comment by robcole** [comment]
@snuggs Load order appears to be exhibiting different behaviors in Edge, perhaps IE11 as well (doing some cross browser testing currently)

Happy to draft up some text once I'm 💯 confident in the behavior in multiple browsers, but at the very least I'm seeing differences in error logs based on when the polyfill is loaded. Still digging into ways to get the polyfill itself loaded for now, just to move on to the next phase of debugging this.

---

# Polyfill Loaded First 
(no snuggsi errors, only polyfill errors)
![image](https://user-images.githubusercontent.com/52430/29840513-25787ea2-8cb7-11e7-82a5-b05c229dd481.png)

# Polyfill Loaded Second
![image](https://user-images.githubusercontent.com/52430/29840460-f5aa6618-8cb6-11e7-94ce-1c24dcb92092.png)

**Comment by snuggs** [comment]
... And I say ... Let's call the whole thing off @robcole ;-) /cc @brandondees #143

**Comment by snuggs** [comment]
Fixed. https://github.com/devpunks/snuggsi#easy-installation

![capture d ecran 2017-09-14 a 09 40 25](https://user-images.githubusercontent.com/38223/30432833-cfc4fc20-9930-11e7-8919-2cbea820368a.png)
