### ISSUE TITLE
Content Negotiation: `Content-Type` is being set incorrectly

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#142]
Should be `application/ecmascript` _preferably_. `application/javascript` _classically_

The site should respond with `Content-Type: text/html` for browsers navigating to root. And `Content-Type: application/javascript` for `<script src=...>` tags which fetch using a `Accept: application/javascript` rule in the request as speced by the whatwg/dom.

I believe you picked up on this @brandondees 

![capture d ecran 2017-09-14 a 10 10 56](https://user-images.githubusercontent.com/38223/30435760-91e61152-9938-11e7-8e3d-00831a71c89e.png)

**Comment by snuggs** [comment]
![capture d ecran 2017-09-14 a 10 10 56](https://user-images.githubusercontent.com/38223/30435760-91e61152-9938-11e7-8e3d-00831a71c89e.png)

**Comment by RobertChristopher** [comment]
Interesting conventions of addressing the type as `application/ecmascript`.
Javascript is an extended implementation of the ECMAScript specification. Is there any reason you have configured the project to this convention? @snuggs

**Comment by snuggs** [comment]
@RobertChristopher Developer ergonomics. `application/ecmascript` `.es` immediately tells me it's precompiled. Javascript `.js` let's me know i probably didn't write that. It's been such an ease cognitively. Lots less resistance to the idea than I had last year. Many keep denying this but when I tell them to change the existing documentation it rarely gets changed. ;-) I'm just following a convention around the docs/specs.  /cc @tmornini 

![capture d ecran 2017-10-21 a 21 19 32](https://user-images.githubusercontent.com/38223/31857184-9991e0a4-b6a5-11e7-91ef-92565b24465c.png)
