### ISSUE TITLE
Add PR and Issue Templates

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#146]
@pachonk @mrbernnz can you champion this article? Please and thank you!

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by brandondees** [comment]
I'm working on pushing through something for this for our team, maybe we can use what we come up with as a conversation starter for this one.

**Comment by snuggs** [comment]
@brandondees @mrbernnz was this supposed to close or still some things to button up.

**Comment by brandondees** [comment]
looks like it's already merged

**Comment by mrbernnz** [comment]
@snuggs Was there something you wanted to bring up to discuss?

**Comment by snuggs** [comment]
Nope all clear @mrbernnz. Thanks for reaching out! <3
