### ISSUE TITLE
Add Git Point

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#150]
@mrbernnz has a request for [GitPoint](https://github.com/gitpoint/git-point). Please provide some info. Looks pretty cool!
/cc @brandondees @tmornini 

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by mrbernnz** [comment]
@snuggs Simple free mobile app that you can view the mostest important notification on the repos you follow. It's free as well. I switched to this for a desktop version [Octobox](https://github.com/octobox/octobox#desktop-usage).

**Comment by snuggs** [comment]
SWEEET. I'll let @brandondees or @tmornini give feedback and if that's ok then right as rain. Not more of a block @mrbernnz  just thought it was a good "stop let's look at this thing over here" As i've never heard of it. Thank you so much!

**Comment by mrbernnz** [comment]
@snuggs I don't know if it's that big of a deal. But ok.

**Comment by brandondees** [comment]
for public/open source repos, i don't feel strongly about it if it's not getting admin privileges or anything like that. the concern would be if the app has the authority to do evil things like rewrite git history, etc. and for any reason behaves maliciously or is buggy enough to do something bad on accident.

**Comment by snuggs** [comment]
@mrbernnz not that big of a deal yes. But valid concerns of @brandondees. As i said before more of an awareness issue than anything else as i've never heard of before. I already know you wouldn't introduce something without vetting it. But just because you know about this be careful assuming everyone has your level of understanding.

**Comment by mrbernnz** [comment]
@brandondees Sorry for the late reply, but no it doesn't have write privileges. Nor does it ask for it. It's a simple app to read github notifications.

**Comment by brandondees** [comment]
@mrbernnz if that's the case then i have no issues with allowing it.

**Comment by mrbernnz** [comment]
👍

**Comment by snuggs** [comment]
me too @mrbernnz if you need write privs lemme know. Just gotta move on it :-) <3 Let us know what you need out of your way so you have no blockers my good man.

**Comment by mrbernnz** [comment]
Ok @snuggs

**Comment by pachonk** [comment]
How is git point? Is it around the best mobile app? I've been using web and that just doesn't suffice

**Comment by snuggs** [comment]
@mrbernnz

**Comment by mrbernnz** [comment]
@pachonk I like it for it's simplicity. The UI is good and not cumbersome. If you are looking for a good desktop app that does the same. You can take a look at: [Octobox](https://github.com/octobox/octobox)
