### ISSUE TITLE
🐞  bug found 11/22/17: snuggsi.min.js:1 Uncaught TypeError: e[n].map is not a function

### ISSUE THREAD

**Issue by johnrlive** [devpunks/snuggsi#157]
1. Console error:

![menu-item](https://user-images.githubusercontent.com/535279/33135775-64df6342-cf71-11e7-8aa9-19e173172a7d.png)

```
snuggsi.min.js:1 Uncaught TypeError: e[n].map is not a function
    at TokenList.bind (snuggsi.min.js:1)
    at HTMLElement.Custom.n.render (snuggsi.min.js:1)
    at HTMLElement.Custom.n.connectedCallback (snuggsi.min.js:1)
    at t.upgrade (snuggsi.min.js:1)
    at Array.map (<anonymous>)
    at t.define (snuggsi.min.js:1)
    at snuggsi.min.js:1
    at index.html:16
```

2. index.html attached

![index_html_ _components](https://user-images.githubusercontent.com/535279/33135851-97acd2c8-cf71-11e7-806a-79bb05dea6aa.png)

```
<!DOCTYPE html>
<script src=https://unpkg.com/snuggsi></script>
<title>menu-item</title>

<menu-item>
<header>
    {name}
</header>

</menu-item>

<script>

    Element `menu-item`
    (class extends HTMLElement{
        onconnect(event) {
            alert(this)
        }
    get name() { return "Ice Tea" }
    })

</script>
```

**Comment by snuggs** [comment]
@johnrlive 🙏  thanks for this.

**Comment by johnrlive** [comment]
@snuggs my pleasure homie! 🙏

**Comment by mrbernnz** [comment]
@snuggs Do you mind if I jump on this?

**Comment by snuggs** [comment]
@mrbernnz  DO IT DO IT! Don't ask for permission.... apologize for mistakes. @tmornini  taught me ;-)

**Comment by snuggs** [comment]
@mrbernnz  @johnrlive Fixed in https://github.com/devpunks/snuggsi/commit/6267e1beccd4512a0572ebf62eeda34ebda62abf
