### ISSUE TITLE
Help wanted: clear explanation of how ES class declarations work scoping-wise.

### ISSUE THREAD

**Issue by brandondees** [devpunks/snuggsi#16]
I'm missing some documentation / instruction on how to use functions defined in ES class declarations from within other functions defined in the same class declaration. 

I've experimented with various combinations of `this.func()` `get func()` `func()` `this.func` etc. and while the properties render into the element's template contents as expected, I can't get the same value into another function context for use in behavior. I'd like some help finding or creating some clear and comprehensive documentation about how this works exactly, and what the standard/best practices are for it.

**Comment by snuggs** [comment]
@brandondees i'm going to punt this off to @VicenteRD and @mrbernnz. They seem to grok the conventions the most. I thought there were 4 conventions @mrbernnz showed me there were 6. /cc @pachonk might want to keep :eye: on this one as well as there are conventions.

**Comment by brandondees** [comment]
yeah i've read the MDN info but i've been stumped on what is allowed or not allowed in terms of defining functions that reference other functions (or properties) in the class expression. i'm used to ruby where anything goes.

**Comment by snuggs** [comment]
@brandondees hopefully this clears up some pain. This is pretty much the "de-fact-o standard" in understanding classes in ES6.

Will provide documentation of how snuggsi uses these principles in a thorough readme. For now this document MUST be groked. Be sure to bring over your ruby conventions. /cc @mrbernnz @janz93 @VicenteRD @robcole @albertoponti

http://2ality.com/2015/02/es6-classes-final.html
