### ISSUE TITLE
Add `is` attribute for Custom Elements

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#167]
https://github.com/whatwg/html/commit/e5dc6bf18f356225d90decc47ac6ed3be94728a7
https://github.com/w3c/web-platform-tests/pull/9508
https://github.com/whatwg/html/issues/3402
https://github.com/whatwg/dom/pull/566

**Comment by GeorgeTailor** [comment]
Webkit safari devs stated that they would never implement `is`. So why bother with it?
[stats](https://gs.statcounter.com/browser-market-share) show that almost 20% use Safari either desktop or mobile.

**Comment by snuggs** [comment]
@GeorgeTailor have a ticket reference? I'd be MORE THAN HAPPY to close this issue. Like watching paint dry. 

[Have asked the team to chime in](https://github.com/web-platform-tests/wpt/pull/9508#issuecomment-637494978).

Added you as a contributor.

**Comment by GeorgeTailor** [comment]
https://github.com/w3c/webcomponents/issues/509#issuecomment-224212371
That was quite a discussion with almost 500 comments xD

**Comment by snuggs** [comment]
@GeorgeTailor copy that! I think that's a good enough reference. I remember that long conversation. Let's close this out! Can always reopen it later. Feel free to skim through any other issues. I'm sure you have already xD.

/cc @rianby64
