### ISSUE TITLE
Add TRACE to Safe Methods

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#168]
@tmornini @brandondees @kurtcagle @btakita I see the words...But difficult to put together sentences:

### HTTP Spec 9.8 `TRACE`

https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.8

> 9.8 TRACE
>
>The TRACE method is used to invoke a remote, application-layer loop- back of the request message. The final recipient of the request SHOULD reflect the message received back to the client as the entity-body of a 200 (OK) response. The final recipient is either the origin server or the first proxy or gateway to receive a Max-Forwards value of zero (0) in the request (see section 14.31). A TRACE request MUST NOT include an entity.
>
>TRACE allows the client to see what is being received at the other end of the request chain and use that data for testing or diagnostic information. The value of the Via header field (section 14.45) is of particular interest, since it acts as a trace of the request chain. Use of the Max-Forwards header field allows the client to limit the length of the request chain, which is useful for testing a chain of proxies forwarding messages in an infinite loop.
>
>If the request is valid, the response SHOULD contain the entire request message in the entity-body, with a Content-Type of "message/http". Responses to this method MUST NOT be cached.

I will add `TRACE` to `SAFE_METHODS` in #164 but will save actual implementation within `Resource` for a subsequent PR related to this issue.

**Comment by brandondees** [comment]
seems like there are a number of security problems with supporting it, and the universal recommendation is to keep it strictly disabled: https://www.beyondsecurity.com/scan_pentest_network_vulnerabilities_http_trace_method_xss_vulnerability

**Comment by snuggs** [comment]
@brandondees MY MAN 50 GRAND! I'm gonna have to weigh in on this. How the heck is it still in the HTTP spec @tmornini ?

**Comment by snuggs** [comment]
@brandondees  so sticking to the following (As defined in MDN) is optimal?

VERY interesting because this means all Javascript servers (And quite possibly ruby servers as well) ALL support TRACE. For instance with node the canonical `HTTP` native library has TRACE.

https://github.com/nodejs/node/blob/bc690e9ef52bebc34cad7ddb40e74472bcb272ca/test/parallel/test-http-methods.js#L38

That would be kinda a big deal to bring awareness to "out of the box". YES?

![capture d ecran 2018-04-07 a 17 06 25](https://user-images.githubusercontent.com/38223/38460352-141d52c2-3a86-11e8-99a8-c13f5435f046.png)

**Comment by brandondees** [comment]
Well, I hadn't seen it used anywhere before and the type of functionality it's supposed to have seemed like the kind of thing we usually try to prevent servers from doing so I just did a quick search for "http trace security" and found a number of "just disable it" tips from various sources. Seems like it's normally dealt with at the apache / nginx layer rather than on the application side, so it's not surprising it's been left untouched in frameworks that all expect to be behind one of those.

**Comment by brandondees** [comment]
documentation on the exact risks and exact best practices wasn't immediately obvious based on my quick search, so maybe it's not that big of a problem, maybe it's just universally disabled by everybody to avoid thinking about it in more detail, or maybe i just didn't look long enough  to find more clarity about what the exact implications and tradeoffs are (what, 20 seconds ain't thorough research?)

I can't think of any obvious use case for this feature in the first place, so I'm assuming we don't really need it. From a security standpoint, I'm a big believer in not shipping attack surface area that isn't well justified.

**Comment by snuggs** [comment]
@brandondees hmmmm.... leaning more towards agreeing with you. Perhaps not a feature but a punt/WIP? Tom and I have been revisiting some parts of the HTTP spec and realizing there is a ton that was just an afterthought that developed into anti-patterns because of monkeys on laddars. (myself included) /cc @tmornini 

![](
![image](https://user-images.githubusercontent.com/38223/38711735-7d77b0ba-3e95-11e8-94ea-3e325bc2347d.png))

**Comment by brandondees** [comment]
yeah just because something's part of a spec doesn't mean it's right. some
of these things were designed before internet security was even a concept,
and may now be obsolete even though there's not a new spec to remove them
