### ISSUE TITLE
" Custom element name must contain a hyphen "

### ISSUE THREAD

**Issue by ltdan1999** [devpunks/snuggsi#170]
❤️

I do not use hyphenated custom element names. 

on some page loads the script will fail to define custom element
many it works just fine

was wondering if maybe I'm loading something out of order...

using current [build](unpkg.com/snuggsi)

[source](https://github.com/ltdan1999/dmt)

thanks snuggs 💎

**Comment by snuggs** [comment]
@ltdan1999 did you get this all sorted out?

Actually hyphens are a mandatory part of the custom element name. Although frameworks like React use [camel casing[(https://en.wikipedia.org/wiki/Camel_case) for their _"custom elements"_, in actuality has been made a part of the spec. Please see https://github.com/devpunks/snuggsi/issues/86

/cc @tmornini @brandondees @btakita
