### ISSUE TITLE
gittr chat for devpunks or devpunks/snuggsi

### ISSUE THREAD

**Issue by btakita** [devpunks/snuggsi#171]
There's so many chat clients out there, which is why gittr is a nice public web chat interface for github projects.

For example, the gittr channel would be:
https://gitter.im/devpunks/snuggsi

It's considerably more lightweight to sign into than slack & it would allow people to lurk on devpunks related conversations, along with showing updates to github issues.

**Comment by snuggs** [comment]
@btakita great idea!

How i didn't get this notification is beyond me lol.

**Comment by btakita** [comment]
@snuggs Looks like people are moving to discord.

**Comment by 0xhjohnson** [comment]
Can I get a discord link? Have a question about polyfills for ie

**Comment by snuggs** [comment]
@0xhjohnson copy that! We haven't done one yet as suggestion from @btakita but good to see you here! We have a ton of experience polyfilling web components so as of now we don't have a gitter. Got the Rails slack channel where we discuss front end. But if you submit an issue and ping me on it we'll make the discussion a priority.

/cc @RobertChristopher @brandondees

**Comment by snuggs** [comment]
@btakita @0xhjohnson  your thoughts on this? Some people have been recently having issues with gittr it seems.

**Comment by btakita** [comment]
Discord seems to be the way to go nowdays.

**Comment by snuggs** [comment]
Copy that @btakita closing this one (for now)
