### ISSUE TITLE
Fix Dependency Alerts

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#180]
@tmornini @brandondees you see this is why I itch when it comes to dependencies and why they should be kept to a minimum.
![capture d ecran 2018-12-10 a 20 46 41](https://user-images.githubusercontent.com/38223/49772918-ff2d2500-fcbc-11e8-8994-f6e3fc2dd610.png)
![capture d ecran 2018-12-10 a 20 46 31](https://user-images.githubusercontent.com/38223/49772919-ff2d2500-fcbc-11e8-9b2c-9ee5efc0f9c6.png)

**Comment by brandondees** [comment]
speaking of, `bin/serve` and whatnot don't even run on current nodejs anymore, it might be time to do some larger scale pruning and migrating
