### ISSUE TITLE
Shrink NPM Package Size

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#182]
No wonder npm publishing takes a minute. Seems to be packaging EVERYTHING. I believe we can use a setting within `package.json` that would allow white/black labeling.

![capture d ecran 2018-12-10 a 22 15 17](https://user-images.githubusercontent.com/38223/49776252-44575400-fcc9-11e8-9192-380738edd8a8.png)

**Comment by brandondees** [comment]
haha whoops

**Comment by snuggs** [comment]
@RobertChristopher @brandondees  now causing JS Stack trace errors that prevent from deploying. On it now. Le sigh....Gotta stop using this as a local server to store my heavy metal mp3s 😂 
![capture d ecran 2018-12-19 a 07 45 31](https://user-images.githubusercontent.com/38223/50221143-3a38f380-0362-11e9-857e-6124bab1c45e.png)
