### ISSUE TITLE
Fix JSStandard Code Style Issues

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#20]
https://github.com/feross/standard

**Comment by snuggs** [comment]
Relative to #101 /cc @tmornini @brandondees. We already abide by most. A few formatting hickups in the codebase. But this may be the "lint"er @brandondees was talking about.

**Comment by snuggs** [comment]
Fixed in #124 but never closed.

**Comment by grepsedawk** [comment]
Well hi there

**Comment by brandondees** [comment]
@snuggs pro tip: [you can auto-close issues from the commit or PR message](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)

really happy to see some maintenance activity again. let me know if there's anything i can do to assist.
