### ISSUE TITLE
Incommunicado?

### ISSUE THREAD

**Issue by tmornini** [devpunks/snuggsi#210]
Hey buddy.

Literally happy to see you’re writing code.

I think I may have lost ability to communicate with you.

Call me!

**Comment by brandondees** [comment]
same here

**Comment by cristhiandick** [comment]
Dido

Regards,
Cristhian

**Comment by RobertChristopher** [comment]
I'll submit a PR & start working on this issue! #FreeJewelry

**Comment by tmornini** [comment]
@snuggs Where are you buddy? We all miss you?

Again, super happy to see you're writing code, but am very concerned by your absense.

**Comment by tmornini** [comment]
> Dido

[Are you a fan? 😄](https://www.didomusic.com)

**Comment by snuggs** [comment]
@tmornini @RobertChristopher #ThankYou 🙏🏽 

<a href=https://www.youtube.com/watch?v=1TO48Cnl66w>
![Capture d’écran 2021-01-01 à 19 31 57](https://user-images.githubusercontent.com/38223/103448489-3f76eb80-4c68-11eb-85c8-e03257c69ca4.png)
</a>
