### ISSUE TITLE
Slack link not working

### ISSUE THREAD

**Issue by caroso1222** [devpunks/snuggsi#211]
Great work with snuggsi!

I realized this link in the README lands you into an empty Slack page. 

https://slack-files.com/T03JT4FC2-F151AAF7A-13fe6f98da

<img width="927" alt="Screen Shot 2020-07-24 at 12 16 41 PM" src="https://user-images.githubusercontent.com/3689856/88417459-90281580-cda7-11ea-9b83-08a0a6292fb4.png">

**Comment by snuggs** [comment]
@caroso1222 fixed in https://github.com/devpunks/snuggsi/commit/99b15c97f74d727bbb12de4d7015f7c087978a42.

Check your email. Welcome aboard!
