### ISSUE TITLE
What is the reason for the limited npm/node engines?

### ISSUE THREAD

**Issue by JoshuaBehrens** [devpunks/snuggsi#212]
## Expected Behavior
I can just do `npm i snuggsi`

## Current Behavior
It tries to install on `npm i snuggsi` but fails with
```
Unsupported engine for snuggsi@0.13.198: wanted: {"npm":"5.0.x","node":"9.8.x"} (current: {"node":"14.4.0","npm":"6.14.4"})
```

## Possible Solution
Do not define any engines in such a limiting manner.

## Steps to Reprod(uce)
1. Have the latest node/npm
2. `npm i snuggsi`

## Context
I want to try to integrate snuggsi into my one of my webpack based projects as it sounds pretty neat. I stumbled upon this limitation. What is the reason for these engine entries? I was looking into the git history but was not very successful getting the reason.

## Your Environment
* Version used: 0.13.198
* Environment name and version: node 14.4, npm 6.14.4
* Operating System and version: Ubuntu 20.04

**Comment by brandondees** [comment]
I think it just hasn't been updated in a long while. A PR would be appreciated.

**Comment by JoshuaBehrens** [comment]
So a possible solution is to remove the constraints completely or are these needed?

**Comment by brandondees** [comment]
I think the minimum may be a hard requirement, but I think an upper constraint is just a question of testing
