### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by eldoy** [devpunks/snuggsi#226]
How do I do server side rendering?

**Comment by snuggs** [comment]
@eldoy great question! didn't really think about it as just using in the browser is so fast. However i'm sure an implementation can be done. The rendering algorithm is like 20LOC. Thoughts? Examples?

**Comment by eldoy** [comment]
@snuggs There is no need for this library (or any other library really) when you can just use JS functions that returns template strings:

```js
function link({ url, text }) {
  return `<my-link><a href="${url}">${text}</a></my-link>`
}
```

This works both on server and browser (isomorphic even) with 0 (zero) dependencies. Is it worth spending time on creating something that is inferior to what is already working perfectly just for some syntactic sugar?

**Comment by snuggs** [comment]
Interesting...probably just need some sort of _"node parser"_. [Under the hood we use the _sparsely documented_ TreeWalker](https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker). What is an advantage is whatever other libraries are using to SSR can guarantee it is orders of magnitude more complex. We just use `TreeWalker`. Wonder if there is anything lighter than JSDOM. Or whatever others are doing. Custom Elements ARE bonified DOM elements. Just thinking out loud.
