### ISSUE TITLE
Make everything from ./examples/ available available via gh-pages

### ISSUE THREAD

**Issue by pachonk** [devpunks/snuggsi#24]

**Comment by snuggs** [comment]
oh wow NVM you already started. LOLZ @pachonk #GreatMindsThinkAlike /cc @brandondees

**Comment by snuggs** [comment]
Fixes #5

**Comment by snuggs** [comment]
@pachonk just decided to write a script. https://github.com/devpunks/snuggsi/blob/master/publish
