### ISSUE TITLE
Consider a modular design of snuggsi

### ISSUE THREAD

**Issue by pachonk** [devpunks/snuggsi#25]
Just something I wanted to bring up, but snuggsi is growing at an amazing rate!
Things like the fileuploader that @VicenteRD is building could be seen as "Out of the original scope of snuggsi", and could add to the overall repository's size when it may be a non-essential piece.
Have you considered going a modular snuggsi approach where you would have a base (let's say around 1kb) then adding literal "plugins" or "modules" to add additional functionality?

Just an idea I had floating around my head a bit the last day or two.

**Comment by brandondees** [comment]
yeah I think keeping it all in the main sandbox repo for now is ideal, but as it gets closer to "consumer ready" it'll be preferable to isolate the individual pieces in keeping with the "only take what you need" minimalistic spirit, and then just link out to all that stuff from the main documentation / examples repo

**Comment by brandondees** [comment]
the package pulled as an NPM dependency should really only be "the actual code you're using" and a little bit of surrounding metadata and documentation

**Comment by snuggs** [comment]
Might be able to get @christiandick help on the README as well.

True @brandondees only thing an `npm install snuggsi` would give them is the dev server. We can be more explicit about that. /cc @pachonk

**Comment by snuggs** [comment]
@pachonk may want to check out this issue as well. @brandondees created it and we have been using it as a north star with all the examples coming through. https://github.com/devpunks/snuggsi/issues/5

**Comment by snuggs** [comment]
Closing this @pachonk . As i think we have this sorted out. Clone repo and `npm browse`  or yarn or whatever you use and off to the races. 

http://snuggsi.herokuapp.com for online version. Also each major "library" in root has it's own README.md now.

**Comment by pachonk** [comment]
Yeah, this should be closed. Thanks
