### ISSUE TITLE
for each console copy/paste example, save readers a step and give a link to a live demo

### ISSUE THREAD

**Issue by brandondees** [devpunks/snuggsi#3]
codepen or jsfiddle or whichever tool works best for script demos, but set it all up so all they have to do is click once to see what it does in the browser

**Comment by snuggs** [comment]
I think we have this covered now @brandondees /cc @pachonk 
 @mrbernnz @VicenteRD https://github.com/devpunks/snuggsi/blob/master/examples/index.html
