### ISSUE TITLE
Choose TLS certificate provider

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#34]
https://www.sitepoint.com/file-bundling-and-http2/

**Comment by snuggs** [comment]
@tmornini what's this HSTS and why 2 years and why does the rating go from A to A+? Forgive me but you know this context is my insecure zone. https://twitter.com/returnnull/status/821809973688750080

**Comment by brandondees** [comment]
HSTS is a standard for telling the browser "use https, and always use https in the future, don't even ask for port 80 again" which, when enabled and respected, avoids the initial plaintext request that gets redirected, preventing a vector for man in the middle hijinks

**Comment by brandondees** [comment]
Because the HSTS status is cached for a long time, it's not enabled by default, because you can't un-do it once somebody visits and receives the header

**Comment by brandondees** [comment]
there are sometimes legacy reasons to not be able to strictly enable https-only mode, but IMHO for new sites there's no good excuse not to go 100% secure. incidentally the browser vendors also maintain HSTS preload lists, which you can submit your domain to, which will cause the browser to act as if it has already received the HSTS directive before even the first request to the domain is made, eliminating that final MITM vector entirely.

**Comment by tmornini** [comment]
👍 for HTTPS only.

As for TLS certs, LetsEncrypt and/or [AWS Certificate Manager](https://aws.amazon.com/certificate-manager/)

**Comment by snuggs** [comment]
Oh man so happy to have you guys. @tmornini  knows I get this stuff but the actual implementation of devops is where my house of cards blows over.

Thanks so much. We'll address this in the week to come.

**Comment by mrbernnz** [comment]
Recommended implementation by Lets Encrypt: https://certbot.eff.org/

**Comment by tmornini** [comment]
@mrbernnz If this will be hosted on AWS, particularly S3/CloudFront, then [AWS Certificate Manager](https://aws.amazon.com/certificate-manager/) would be simpler and less expensive as no server instance(s) would be required.

Also, S3/CloudFront will deliver the files with lower latency as CloudFront will serve them from an AZ that is low-latency to the requestor.

**Comment by mrbernnz** [comment]
@tmornini thanks for the knowledge.

**Comment by tmornini** [comment]
👍

**Comment by brandondees** [comment]
AWS's free cert thing is basically their own branded version of Let's Encrypt, because they want to create lock-in.

**Comment by tmornini** [comment]
"Basically" except that they auto-renew and update load balancers, etc. automatically.

No real lock in here, using it is free, avoids having an instance, and can be trivially replaced if. We'd be.

More likely to be locked in by convenience of R53, S3, CloudFront, convenience, reliability, performance and cost savings...

**Comment by brandondees** [comment]
Yeah I don't mean you can't get away from it just that AWS has a proprietary version of everything so that transitioning away is less of a "keep using the standard stuff you've been using and take it elsewhere" proposition. Let's encrypt also auto-renews and whatnot, so there's not a lot of difference that they didn't artificially create.

**Comment by tmornini** [comment]
> Let's encrypt also auto-renews and whatnot

Let's encrypt doesn't auto-renew, certbot does as part of a polling routine which requires configuration and a server to run on which require security patches and a bunch of other admin crap that there's no point in dealing with to serve static files. 😄

**Comment by snuggs** [comment]
OH SO certbot is  like "Pingdom" from back in the day @tmornini @brandondees ? 

Basically keeps a request going to keep up sleepy instances. Oh this makes sense I see. /cc @mrbernnz

**Comment by tmornini** [comment]
> certbot is like "Pingdom" from back in the day

No. Certbot is software that runs on the web server instance, or elsewhere.

It keeps state in the local filesystem, including a config file for the domains it's handling.

You run it in a crontab, or any other way to invoke it regularly, and it makes requests to letsencrypt for new certificates on a regular basis so that the 90 day certificates that letsencrypt provides don't expire.

**Comment by snuggs** [comment]
@tmornini @brandondees That awkward moment when you do nothing and it fixes itself. ;-)

Since April this year 👉 https://zeit.co/blog/automatic-ssl-with-now-lets-encrypt

**Comment by rianby64** [comment]
Amazing! @snuggs
