### ISSUE TITLE
better "Why?" in the readme

### ISSUE THREAD

**Issue by brandondees** [devpunks/snuggsi#4]
I suggest making WHY? an h2 heading, to make it easier to find and focus on separately from all the content which is irrelevant until someone gets this part

I also think the why section can be re-written to better emphasize what problems it's solving. It can also call out the relevance in terms of WHY NOT X ALTERNATIVE TOOL? I recommend concise bullet lists for these points, hyperlinks for additional explanation optional.

A lot of what's in that section now is really more like a back story for how this project came to be, which is nice to be able to see but it doesn't deliver that instant candy gratification that we're used to getting, so I think getting to the key points up front and center first is worthwhile, before getting into the more long form background explanation.

**Comment by snuggs** [comment]
@brandondees 
https://github.com/devpunks/snuggsi

Is this suffice enough to close this issue?

**Comment by brandondees** [comment]
@snuggs MUCH better, let's close it for now and i'll open new issues when i have more ideas about it
