### ISSUE TITLE
Automate render after event handler

### ISSUE THREAD

**Issue by janz93** [devpunks/snuggsi#46]
## Default
currently, we call always `render`
```javascript
static onnext () {
  this.date_from_month (+1)
  this.render () 
}
```

We can implicitly render on all event handlers.
```javascript
static onnext () {
  this.date_from_month (+1)
  // this.render () // automagically gets rendered.
}
```

## Preventing Default
Inject the event object into the handler
[MDN Event Object](https://developer.mozilla.org/en-US/docs/Web/API/Event)
```javascript
static onclick (event) {
  event.preventDefault () // stops render

  alert (this.textContent)

  this.render () // explicitly render component
}
```

**Comment by snuggs** [comment]
Was not able to use `event.preventDefault ()` API as we would have to monkey patch. Introduced a "sugar" method `event.prevent ()` which will be available to all declared `on*` events _(i.e. `static onclick (event) {}`)_

Conversely we also introduced the `return false` convention for those familiar with jQuery.

```javascript
(class extends HTMLElement {
  static onclick (event) {
    event.prevent () // pre-operation disable of rendering

    alert (this.textContent) // operation
    // this.render () // always have option to explicitly render
    return false      // post-operation disable of rendering
  }
})
```
@janz93 @RobertChristopher @brandondees @btakita @mrbernnz @scottmacdowell

**Comment by brandondees** [comment]
is this to reproduce preventDefault()'s behavior or to prevent snuggsi from rendering? if the latter, i think `prevent()` is not self-descriptive as it could be

**Comment by snuggs** [comment]
latter @brandondees. API suggestion? To be honest i'm good with `return false` however really wanted to have `event.preventDefault ()` and i agree is confusing unless it actually Prevents the Default.

I think what i realized from your statement is `prevent ()` is fine if it actually calls `preventDefault` AND prevents `this.render` which is a "default behavior" that is prevented. (as per the spec).

Please advise.

**Comment by snuggs** [comment]
> is this to reproduce preventDefault()'s behavior or to prevent snuggsi from rendering? if the latter, i think prevent() is not self-descriptive as it could be

Actually @brandondees on second thought not an OR situation but an AND situation.

**Comment by brandondees** [comment]
nah i think the `prevent()` name is confusing UNLESS it's just a contextual wrapper for `e.preventDefault()` since that's the only other thing it sounds like.

if its purpose is to prevent default AND prevent render, then maybe we start by calling it `preventDefaultHooks()` or something a little more descriptive like that. if it's only render() then `preventRender()`

i'm not sure i've grasped yet where the `return false` factors in or what it means

**Comment by snuggs** [comment]
@brandondees some (ancient) insight as to the conventions. https://stackoverflow.com/questions/1357118/event-preventdefault-vs-return-false

**Comment by brandondees** [comment]
> Note that this behaviour differs from normal (non-jQuery) event handlers, in which, notably, return false does not stop the event from bubbling up.

ah ok so there's a scope traversal thing going on also independent of preventDefault()
