### ISSUE TITLE
JSFiddle doesn't load HTML Imports

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#47]
@brandondees @RobertChristopher  For some reason the `<link rel=import>` doesn't work on JSFiddle but does work from our examples.

Do keep in mind JSFiddle evaluates it's REPL using an `<ifame>` perhaps some content policy issues?
A mystery to me ❓ ❓ ❓ 

Have also tweeted to GOOGLE Chrome Dev team. 
https://twitter.com/snuggsi/status/868884622683328513

## Web Component
- `<header-group>` - https://snuggsi.herokuapp.com/examples/header-group

## JSFiddle example - https://jsfiddle.net/xqycvrpL

![capture d ecran 2017-05-28 a 13 32 17](https://cloud.githubusercontent.com/assets/38223/26530809/29ccab14-43aa-11e7-9ee8-5d684df04a51.png)

**Comment by RobertChristopher** [comment]
@snuggs It appears running the file locally encounters the same errors.

**Comment by snuggs** [comment]
@RobertChristopher have notified JSFiddle https://twitter.com/snuggsi/status/873159699729973248

**Comment by RobertChristopher** [comment]
@snuggs Any status on this?

**Comment by snuggs** [comment]
wow @pachonk first time i get to use this myself /cc @brandondees hehe https://twitter.com/slicknet/status/782274190451671040

**Comment by pachonk** [comment]
I'm laughing inside so hard that I blow a little more air out of my nose than normally.

**Comment by brandondees** [comment]
I read it as "i blow a little more _hair_ out of my nose than normally" and was gonna suggest you one of these lol: https://www.amazon.com/Groom-Mate-Platinum-Nose-Trimmer/dp/B000EBFJXS/?th=1

**Comment by pachonk** [comment]
Wow! Only $20!

**Comment by brandondees** [comment]
yeah it's kinda pricey but it's manual rather than electric, compact and portable, etc. so IMHO worth it in terms of longevity.

**Comment by pachonk** [comment]
I thought it was cheap.

**Comment by snuggs** [comment]
JS Fiddle has given us solution. Will need polyfill.
