### ISSUE TITLE
show live code examples in a demo site

### ISSUE THREAD

**Issue by brandondees** [devpunks/snuggsi#5]
I know you've already started on this. More examples would be good. Fewer clicks to see all the examples and the code that they're based on would be good, too. I'm specifically thinking of how [ZURB Foundation](http://foundation.zurb.com/sites/docs/tabs.html) demonstrates code snippets alongside various corresponding live implementation examples so you can see what you'll get without having to do anything. They also put it all into one big easy to navigate list that you can scroll through to "window shop" before you decide what to put any effort into using, and everything's also reachable from the nav list on the side in case that's a faster way to get to what you're looking for.

**Comment by snuggs** [comment]
https://github.com/devpunks/snuggsi/issues/24 << This will CERTAINLY help. /cc @pachonk

**Comment by snuggs** [comment]
I think this is ready to go @brandondees however need help from @pachonk on #24 

Can point directly to ./examples/index.html for now. All dependency links were updated today in examples.

What do we need to close this issue?

**Comment by brandondees** [comment]
is github pages live? how do we reach it?

**Comment by snuggs** [comment]
@pachonk ping

**Comment by snuggs** [comment]
http://snuggsi.herokuapp.com
http://snuggsi.herokuapp.com/examples
