### ISSUE TITLE
Named <template> <slot>s not translated during HTMLLinkElement.import

### ISSUE THREAD

**Issue by RobertChristopher** [devpunks/snuggsi#56]
It appears that imported templates are not delegated an initial render call. This leaves the elements within the template to explicitly execute the initial render.

The structures below when executed will display the <hello-world> element in its initial token representation.

- hello-world.html

```html
<template>
  <hello-world>
   Hello {planet}
  </hello-world>
</template
  
<script src=https://unpkg.com/snuggsi></script>
<script defer>

// Element Definition -----------------------------

Element `hello-world`

// Class Description ------------------------------

(class extends HTMLElement {

  onclick ()
    // "automagic" event registration
    { alert (this.textContent) }

  get planet ()
    // "automagic" token binding
    { return 'world 🌎' }
})

</script>
```

- index.html 

```html
<script nomodule src=//unpkg.com/snuggsi/snuggsi.min.js></script>
<link rel=import href=hello-world.html>
```

- result
Hello {planet}

Explicit delegation to the render method within the <hello-world> initialize method will render the tokens, as expected. For example:

```js
...
initialize () {
   this.render()
}
...
```

**Comment by snuggs** [comment]
INTERESTING!!!!!!!!!! Nice pick up @RobertChristopher we can pair on this. I been looking for that bug. We NEED that for imports for sure.

**Comment by snuggs** [comment]
@RobertChristopher Following chain is not being called. Probably the hairiest part of the spec. Thank @brandondees for that one but well worth it. 

https://github.com/devpunks/snuggsi/blob/master/elements/component.es#L27-L29
https://github.com/devpunks/snuggsi/blob/master/elements/global-event-handlers.es#L31-L40
https://github.com/devpunks/snuggsi/blob/master/elements/html-link-element.es

**Comment by brandondees** [comment]
don't "thank" me, i didn't implement anything but a demo! i'm starting to think it's time to be investing in unit tests for these kinds of things though

**Comment by snuggs** [comment]
Well you know i'm a religious tester @brandondees. However I'm feeling build them as they come. Me 2 years ago would have still been working on the test suite. no features.

That said this is the most intricate process so perhaps a valid point. Irony is if you remove the polyfill everything works. SMH.

**Comment by brandondees** [comment]
if that's the case, might be time to start thinking about crafting your own minimal polyfill that does just what's needed

**Comment by snuggs** [comment]
@brandondees @RobertChristopher @janz93 I believe a convention should be to keep snuggsi declaration to the consumer's choosing. I just know we COULD let them define `<script src=//snuggsi>` within `import`ed `<template>`s However if had to make a choice i'd say keep the `<script...>` within master document.

Please advise as this is just a pattern to abide by.

**Comment by snuggs** [comment]
Also @brandondees what I like is I didn't even let @RobertChristopher know about the HTML `<link rel=import>.import` feature. He discovered it all on his own. That's a testament to us having readable source code. 🏆

**Comment by snuggs** [comment]
@RobertChristopher i've deduced the 🐛  down to the `Component.parse ()` API. PR coming soon.

https://github.com/devpunks/snuggsi/blob/master/elements/component.es#L58-L96
