### ISSUE TITLE
Object definitions for interpolated css styling

### ISSUE THREAD

**Issue by RobertChristopher** [devpunks/snuggsi#57]
As of now, declaring functions that return styles to be interpolated into elements requires imperative string concatenation.

I propose the ability to define an object mapping of styles.

Example:
```html
<input style={input_style}>
```
```js
get input_style () {
  return {
    'visibility': 'hidden',
    ...
  }
}
```

A naive implementation would be interpreting objects returned from tokens within the style tag and resolving them to their css representation.  An example abstraction for this is shown below.

```js
const

  createStyle = (params) => {
    return Object.keys(params)
      .filter((i) => params[i])
      .map((param) => {
        return `${param}=${params[param]}`
      }).join(';')
  }
```

**Comment by snuggs** [comment]
@RobertChristopher styling should/can be set with the `.style` property. Also might be a good convention to not declaratively place them inline. This also satisfies the ancient inline problem pattern.  That said... My man @brandondees probably would throw in a `<foo-bar style={style} />` might be a nice convention for inline styles eliminating FOUC (https://en.wikipedia.org/wiki/Flash_of_unstyled_content)

/cc @btakita @mrbernnz @robcole @janz93 

## `HTMLElement.style` MDN
MUST be careful with this one. A repaint is caused on  each mutation. 
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style
- `.setProperty (rule, value)` - https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty

## Custom Element
- https://www.html5rocks.com/en/tutorials/webcomponents/customelements/#fouc

# Other Links
- https://css-tricks.com/authoring-critical-fold-css
- https://stackoverflow.com/questions/5293280/css-pseudo-classes-with-inline-styles
- https://alexsexton.com/blog/2010/09/an-accessible-way-to-stop-your-content-from-flashing-fouc/
- https://jakearchibald.com/2016/link-in-body/

**Comment by snuggs** [comment]
.... That said @RobertChristopher CSS in JS is a SLIPPERY SLOPE. 🎿 :skier:

**Comment by RobertChristopher** [comment]
@snuggs Yes, definitely agree. As many elements maintain application state, it's often desirable to reflect changes in the CSS styling of elements. 

As of now, the document query selector enables that. Dynamic CSS styling through object structure is more elegant and structurally declarative than imperative element manipulation though.

In the Snuggsi conventions, we typically avoid inline styles through the use of stylesheets.
However, at times it may be sensible to manipulate a subset of the attributes (ex: visibility).

Just some thoughts.

**Comment by snuggs** [comment]
Correct @RobertChristopher it's nothing wrong with changing the `Element.style` property but gotta know what you are doing. Like the fact every change to it causes a repaint/reflow (potentially). But usually is the first place people look to change styles with JS. Best to shield people away from that as much as possible.

https://gist.github.com/paulirish/5d52fb081b3570c81e3a

/cc @brandondees @scottmacdowell @btakita

**Comment by snuggs** [comment]
@RobertChristopher may want to take a look at this wiki page as well. https://github.com/devpunks/snuggsi/wiki/TL;DR;-(Too-Long;-Didn't-Read)-DOM-Lessons#rendering-re-flow-re-layout-re-paint

**Comment by RobertChristopher** [comment]
@snuggs Interesting nature of the browser. Any reason as to why it wouldn't assert state mutations before rendering?

**Comment by RobertChristopher** [comment]
@snuggs Yes, I see what you are saying. Definitely should be conscious of the implications involved with a style mutation. I really think this convention provides a sensible abstraction. 

Mutating style state is a common phenomenon within web applications anyway.

**Comment by snuggs** [comment]
@RobertChristopher can/should we close this?

**Comment by pachonk** [comment]
Wait why am I the janitor now?

**Comment by snuggs** [comment]
@pachonk the garbage collector isn't the janitor. He holds one of the most important rolls in software development. And  not only that there was a time a month ago you created like 5 issues. Then came back and swept them all up mad late. Sporadically. I think one of them is still there. Just like a GC it comes when IT wants to. Not when YOU want it to. #GetFamiliar Get VERY Familiar because the GC is not good or bad but a necessary evil. YARRRRRRRRRRR!!!!! https://www.youtube.com/watch?v=RWmzxyMf2cE /cc @brandondees @tmornini @btakita @robcole

**Comment by snuggs** [comment]
@pachonk ❤️  https://github.com/devnacho/mountain_view/issues/52#issuecomment-312513471

**Comment by pachonk** [comment]
<3
