### ISSUE TITLE
show code snippet alongside live demo examples

### ISSUE THREAD

**Issue by brandondees** [devpunks/snuggsi#6]
if we're gonna demonstrate how to use the code to create cool UI bits, it's ideal to show the code and the testable demo right next to each other so it's easy to see what input relates to what output without navigating around between pages or manually experimenting with code to try to replicate something.

**Comment by snuggs** [comment]
@brandondees  Oh this is nice! Starting to get working examples up at https://github.com/devpunks/snuggsi/tree/master/examples

**Comment by brandondees** [comment]
http://www.devpunks.com/examples/infinity-calendar.html 404

**Comment by snuggs** [comment]
Copy that @brandondees becoming mental gymnastics putting it on devpunks. Will update link. Docs coming soon!

**Comment by tmornini** [comment]
@snuggs Time for deployment automation... :-)

**Comment by brandondees** [comment]
@snuggs Was that a typo? I don't see code snippets yet
