### ISSUE TITLE
gh-pages x-flashy page is busted

### ISSUE THREAD

**Issue by brandondees** [devpunks/snuggsi#63]
https://snuggsi.herokuapp.com/examples/x-flashy.html

![image](https://user-images.githubusercontent.com/185732/27271779-43d41f7c-548c-11e7-8d77-f9ae1e499c12.png)

looks like there are some non-https CDN links involved (should be checked for all pages), and browser-sync is still included which probably shouldn't be.

**Comment by brandondees** [comment]
on second look, it seems it's not the only page under /examples with similar problems

**Comment by snuggs** [comment]
It's funny @brandondees the times i DON'T open the console i think "Must be something i'm doing currently it will pass" this was one of those cases. Will get fixed up ASAP.

**Comment by RobertChristopher** [comment]
@snuggsi Remember, the imports should be protocol agnostic. We can just reduce the 'http://' to '//'.

**Comment by brandondees** [comment]
or really always prefer https when it's known to be available, I think.

**Comment by snuggs** [comment]
@brandondees that's the thing it wasn't known. That said if using `https` from page that assumes `https` will request using `https` so the responsibility would be on the underlying site to be using `https` Which is where we are now but still a few more stops to go on this road to HTTP/2 called the interwebz.

**Comment by brandondees** [comment]
I strongly recommend not using any CDN that doesn't support https, just sayin'
