### ISSUE TITLE
Set <title> within nav-view

### ISSUE THREAD

**Issue by RobertChristopher** [devpunks/snuggsi#64]
We should set document title within the `<nav-view>`

**Comment by snuggs** [comment]
@brandondees this touches on Turbolinks feature. Given the following `<nav-router>`

```html
<nav-router></nav-router>

<main view title='Foo bar'></main>
<main view title='Will not show'></main>
```
Would generate the following
```html
<title>Foo bar</title>

<nav-route>
  <a href=#baz title='Foo bar'>Foo bar</a>
  <a href=#bat title='Will Not Show'>Will Not Show</a>
</nav-route>

<main view id=baz title='Foo bar'>This is visible</main>
<main view hidden id=bat title='Will Not Show'></main>
```

Thoughts? /cc @RobertChristopher @btakita @robcole @janz93 @scottmacdowell

**Comment by snuggs** [comment]
@RobertChristopher seems like `title` property of `history.pushState` doesn't work but is in the spec. So i guess we actually have to do this feature for now. I thought it was working but does not.

A simple `document.title = 'Title coming from targeted main view'` does the trick as you see below.

![capture d ecran 2017-06-21 a 11 25 21](https://user-images.githubusercontent.com/38223/27392334-6b7ca136-5674-11e7-8bc0-f3c1a80e7353.png)
