### ISSUE TITLE
show comparison components implemented in common other styles

### ISSUE THREAD

**Issue by brandondees** [devpunks/snuggsi#7]
for a given demo component (pick the most advanced demo, preferably), show the code and live component for each of the most common ways someone is likely to be comparing this tool to. for example if there's an elaborate datepicker widget that supports a variety of different selection modes and configuration options, show the same thing implemented as a react component, as a polymer component, as an angular directive, and with snuggsi. if the code is really cleaner, more understandable, faster, etc. then it should be able to speak for itself.

**Comment by snuggs** [comment]
i'll see if i can link with @btakita to get a Riot.js example.
