### ISSUE TITLE
<user-list> ReactiveJS sample (still) not working

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#76]
https://github.com/devpunks/snuggsi/tree/master/examples/user-list
https://github.com/devpunks/snuggsi/blob/master/examples/user-list/reactive.es

@RobertChristopher i've carried the football as far as i could with this. The plus side is we were able to remove 60% of the code and get down to a single Mixin.

[_(See mixin documetation here)_](https://developer.mozilla.org/en-US/docs/Glossary/Mixin)
[_Class Mixin documentation_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Mix-ins)

Need some help on crossing the finish line with this one. A GREAT example and learned a ton.

Here are the references I've been using:
- Introduction - https://dacz.github.io/rxr/docs/Introduction.html
- Reducers - https://dacz.github.io/rxr/docs/basics/Reducers.html
- Message Streams - https://github.com/dacz/rxr/blob/master/docs/api/createMessageStreams.md
- Providers - https://dacz.github.io/rxr/docs/api/Provider.html

**Comment by RobertChristopher** [comment]
Any explicit issues you are facing here? @snuggs

**Comment by snuggs** [comment]
Look at the source. It doesn't work lol. I don't know ReactiveJS @RobertChristopher. I left everything that is needed. Gotta read through the links tho.

**Comment by snuggs** [comment]
@RobertChristopher can you PLEASE take a look at this sir? Thank you. in examples/user-list
