### ISSUE TITLE
Issue When Transpiling / Minifying

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#78]
I think there is an issue with Uglify-JS or webcomponentsjs. As it's breaking our functionality in Safari at least within jsfiddle. https://jsfiddle.net/whdLtc5q/

![capture d ecran 2017-07-02 a 01 15 07](https://user-images.githubusercontent.com/38223/27767369-230b21cc-5ec4-11e7-81a7-ef98eb3f3c13.png)

**Comment by snuggs** [comment]
This only comes up  when using minified es6. @pachonk care to test this out?

**Comment by pachonk** [comment]
Hmm, could I get more context to the issue?

**Comment by snuggs** [comment]
@pachonk check out the `dist` readme. It's in the `minification` step. Converting es6 to es5. I think our polyfill uses the same minifier thus creating the same tiny variable names `e`. 

We use this https://github.com/paulovieira/UglifyJS2

**Comment by snuggs** [comment]
@pachonk to be clear i don't know what that first error is. That should cure half your queries. 😜

**Comment by snuggs** [comment]
@angelocordon @robcole @brandondees  come to find out this was a bug in Safari. They have recently fixed it. This is a good thing but requires someone to be forced to update. This bug still lingers for many people on safari who haven't updated. This is a perfect example of by leaning on the specs since they are "living" not every browser will always be at 100%. That being said the onus is on the PLATFORM VENDOR not the developer to update as in this case. The problem is happening when we minify ES6 -> ES6(minified with UglifyJS). I'll get this fixed up after I do a little research on the references.

## Reference Links
  - UglifyJS issue - https://github.com/mishoo/UglifyJS2/issues/1753
  - UglifyJS Pull Request - https://github.com/mishoo/UglifyJS2/pull/1851
  - Webkit Bug - https://bugs.webkit.org/show_bug.cgi?id=171041
  - Webkit changeset - https://trac.webkit.org/changeset/217200/webkit

## Problematic UglifyJS Output
If you notice below the `.assign (e, ...)` is being shadowed by `let e` later within the function. The ECMAScript language has no issue with shadowing variables _(We do this with `Element` vs `window.Element`)_
![capture d ecran 2017-08-22 a 09 58 00](https://user-images.githubusercontent.com/38223/29569149-97e99602-8720-11e7-8d8b-c5601b1605bd.png)
![capture d ecran 2017-08-22 a 09 57 26](https://user-images.githubusercontent.com/38223/29569150-97ed094a-8720-11e7-9f4a-edd8e0948b97.png)
