### ISSUE TITLE
show speed comparison with react and other top alternatives side by side

### ISSUE THREAD

**Issue by brandondees** [devpunks/snuggsi#8]
benchmark numbers are fine, but it might also be fun to have a demo page which loads two implementations of similar functionality side by side in parallel iframes, to race them against each other. the demo could do something inherently slow like iterating data mutations through a long list and re-rendering nested elements based on it.

**Comment by brandondees** [comment]
also it's important to distinguish between first load performance, first iteration performance, and collection performance at various sizes. my understanding is that some of the SPA frameworks start to collapse when rendering or updating large lists or tables of data, which can limit capabilities for some kinds of uses. I think it's useful to be able to see the budget figure that's realistic to work with for a given type of use. For example if you tell me I can have 2-way binding at 60fps on mobile with complex components in a list _up to_ 1000 items long, or 10,000 object properties rendered, or whatever, that's useful to bear in mind when designing my system functionality, as opposed to just having some vague concept of how many millions will crash the browser or that 10-item lists are snappy no matter what.

**Comment by snuggs** [comment]
i'll see if i can link with @btakita to get a Riot.js example as well.

I've already got Angular 2 setup. in a comarison page.

https://github.com/devpunks/snuggsi/tree/master/benchmarks/properties

Related to https://github.com/devpunks/snuggsi/issues/7

**Comment by snuggs** [comment]
@brandondees i'm closing this one. As we can do a side by side but the more I think about it the more we may not want to pick this fight. Ironically i've done some speed improvements that get us in the same range as the rest. But Benchmark wars are known to create strawmen.

If you feel we REALLY need to have this I have zero problem re-opening since your opinion is just as valid. /cc @btakita @scottmacdowell @RobertChristopher @robcole

**Comment by brandondees** [comment]
yeah depends on whether it's being sold as faster or not. something I think prospective users would like to be able to see but if it's not worth the work to set it up then no need

**Comment by brandondees** [comment]
sooner or later someone else will include it in their framework contests

**Comment by snuggs** [comment]
They can even use JSBIN if they want to @brandondees  :-) /cc @RobertChristopher
