### ISSUE TITLE
Assigned Slot Usage

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#80]
Is Assigned Slot usage of any value to use to wrap conventions around?

# `HTMLSlotElement.assignedNodes ()`
- MDN - https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedNodes
- WHATWG Living Standard - https://html.spec.whatwg.org/multipage/scripting.html#the-slot-element

## Prerequisite Reference Links
- [HTML `<slot>` element tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot)
- [`HTMLSlotElement DOM Interface`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement)
- [MDN `Element.slot` property](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/slot)
- [WHATWG Living Standard `Element.slot` property](https://html.spec.whatwg.org/multipage/dom.html#attr-slot)

## Further Learning
- Shadow DOM - https://www.w3.org/TR/shadow-dom/#widl-HTMLSlotElement-assignedNodes-sequence-Node--AssignedNodesOptions-options

**Comment by brandondees** [comment]
giving me work on a sunday, grumble grumble...

**Comment by brandondees** [comment]
i'm loosely familiar with the spec docs etc... what question are we considering the answer to here exactly, @snuggs ?

**Comment by brandondees** [comment]
IMHO the specs don't actually say anything about it yet but i would _assume_ the default magic behavior is at least one-way or two-way data binding between the component's attributes and the shadow dom output (or rendered custom element output, for which shadow dom is a nice enhancement but unnecessary). I believe we already covered that bit in snuggsi. 

I think if the dev-facing behavior is consistent, and we aren't explicitly violating any of the spec guidelines that impact shadow-dom browser implementations etc, we're in good shape... snuggsi can always alter the implementation under the hood keeping the dev-facing behavior identical.

**Comment by snuggs** [comment]
TRUEEEEEE!! No code like No code! Just making sure we cover the areas of the specs we care about. Shadow DOM is shady #PunIntended :trollface:  /cc @tmornini
