### ISSUE TITLE
<to-do>

### ISSUE THREAD

**Issue by tmornini** [devpunks/snuggsi#85]
Speaking with @halorium about snuggsi today, and he mentioned that most JS frameworks (cough) have a TODO app demo and that having one would make it easier to compare with the other frameworks.

**Comment by brandondees** [comment]
yep it's gonna have to happen sooner or later.

**Comment by snuggs** [comment]
@tmornini @brandondees we'll use the [`window.localStorage`](https://github.com/tmpvar/jsdom/pull/1872) Web API. _([more details here]())_

- [Web Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API)
- [Local Storage](https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage)

**Comment by brandondees** [comment]
I'm not initiated on the detailed requirements but best stick with whatever's established for this (not sure if there is a prescription / requirement on persistence at any level): http://todomvc.com/

**Comment by snuggs** [comment]
@brandondees @tmornini there's a (general) spec for this as well.
https://github.com/tastejs/todomvc/blob/master/app-spec.md

Have addressed as checklist item in PR https://github.com/devpunks/snuggsi/issues/89

/cc @halorium

**Comment by snuggs** [comment]
@brandondees @tmornini @halorium Found the comparative examples. Man look.... if this is "A simple TODO in VANILLA JS" then the web is all fucked up!:

- https://github.com/tastejs/todomvc/tree/gh-pages/examples/vanillajs/js

Here's others we can use as a Benchmark (Pun intended)
- https://github.com/tastejs/todomvc/tree/gh-pages/examples

**Comment by snuggs** [comment]
Found this to use as a "Vanilla JS" ES6 reference to the concept of the mixin `Storage (HTMLElement)`

As an aside I think this would be a great Mixin to have as an example anyways.

https://github.com/tastejs/todomvc/blob/gh-pages/examples/vanilla-es6/src/store.js

**Comment by halorium** [comment]
Wow @snuggs, you got busy on this quick. Cool. Excited to see the final product. I have built the Todo MVC app in about 3 different frameworks before so it will really help me understand what you have built.

**Comment by snuggs** [comment]
Found a better "Store" May want to hold on to this one. Thank you RiotJS /cc @btakita 

https://github.com/tastejs/todomvc/blob/gh-pages/examples/riotjs/js/store.js
