### ISSUE TITLE
Site layout's looking kind of janky in chrome at the moment

### ISSUE THREAD

**Issue by brandondees** [devpunks/snuggsi#91]
![image](https://user-images.githubusercontent.com/185732/27935042-49d0d240-626e-11e7-899a-225a78b4df9e.png)

**Comment by snuggs** [comment]
Yeah noticed @robcole experienced the same.

**Comment by snuggs** [comment]
@brandondees found out the layout break. I think it was the length of the `<script>` install. At least on that page. When i added `crossorigin` my layout finally broke like yours.

![layout break](https://user-images.githubusercontent.com/38223/28948495-058169f2-7884-11e7-8548-8ca6766c4efa.gif)

**Comment by snuggs** [comment]
How to update CSS Grid with IE https://medium.com/@elad/supporting-css-grid-in-internet-explorer-b38669e75d66

**Comment by snuggs** [comment]
@brandondees 👉🏽 https://snuggsi.com/#installation

😎 

We already address the missing examples in #118

**Comment by brandondees** [comment]
@snuggs I am pumped to see you back in action, and the snuggsi website back to life!
