### ISSUE TITLE
REMOVE ALL CONTENT CHARSET META TAGS

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#95]
:trollface: AWEEEEEEEEEEE 💩  @brandondees !!! They comin' for your `<meta charset=utf-8>` tag. /cc @tmornini 

https://www.keycdn.com/support/avoid-a-character-set-in-the-meta-tag/

![capture d ecran 2017-07-07 a 05 23 16](https://user-images.githubusercontent.com/38223/27951883-6b31cb2c-62d4-11e7-8226-8f7660467907.png)
![capture d ecran 2017-07-07 a 05 21 51](https://user-images.githubusercontent.com/38223/27951884-6b34293a-62d4-11e7-9e21-c8ea49368ea5.png)

**Comment by brandondees** [comment]
i'm down with the header approach, just gotta make sure it's enabled

**Comment by snuggs** [comment]
@brandondees Fear is the path to Internet Explorer…fear leads to anger…anger leads to hate…hate leads to IE suffering......

![image](https://user-images.githubusercontent.com/38223/27982501-ccbfc046-6370-11e7-9339-d0aab3e63a88.png)

**Comment by snuggs** [comment]
@brandondees I feel @domenic's pain on this one. Here's a little bedtime story for you. Pretty good TL;DR; 

![capture d ecran 2017-07-08 a 00 15 34](https://user-images.githubusercontent.com/38223/27982571-b3c4a4b0-6372-11e7-8aed-ed4854f8d019.png)
