### ISSUE TITLE
Implement TravisCI for automated testing

### ISSUE THREAD

**Issue by pachonk** [devpunks/snuggsi#97]

**Comment by pachonk** [comment]
I can work on this, possibly

**Comment by snuggs** [comment]
Possibly @tmornini has some links to put us in the right direction. Now that we have a pipeline and all.

`./crank` :-)

**Comment by pachonk** [comment]
Oh, I'm good. I've been writing TravisCI configurations for awhile

**Comment by snuggs** [comment]
LOL @ "awhile"... your'e good man! Awesome!

**Comment by tmornini** [comment]
@pachonk #101 is WIP

**Comment by snuggs** [comment]
@pachonk @tmornini closing. Great job on #101 /cc @tmornini @rianby64
